### ISSUE TITLE
get_parameter no longer used in pyPiper

### ISSUE THREAD

**Issue by rcorces** [databio/rnapipe#8]
Hey @nsheff - I was in need of an RNA-seq pipeline and I naturally came here. I went with the Kallisto version since it was the most-recently updated (good idea or bad idea?). I'm not sure if you guys are still maintaining these. Getting this up and running was very smooth with the exception of the following issue:

I think `get_parameter` is no longer used in the newer version of pyPiper. It was changed to `get_first_value` via https://github.com/databio/pypiper/commit/62cc784086c67fa74fa1ce32dba7238acacd2412. At least in the Kallisto pipeline this needs to be changed in the following places:
https://github.com/databio/rnapipe/blob/42ff6b1226edc2ae6f59931f38009917f8ddaa57/src/rnaKallisto.py#L12

and

https://github.com/databio/rnapipe/blob/42ff6b1226edc2ae6f59931f38009917f8ddaa57/src/rnaKallisto.py#L213

I did not find uses of `get_parameter` in the other pipelines, perhaps because they arent really used?

**Comment by nsheff** [comment]
I'd say we are still maintaining these, but we do less stuff with RNA so they are less used... but the kallisto one should work for you, if kallisto is what you want to use.

Yeah -- `get_parameter` is a really useful thing but it wasn't widely used yet -- it looks like we missed this use of it when we made the name change.

I've updated it now here in rnapipe...

**Comment by nsheff** [comment]
by the way, FYI there's a new version of pypiper out just a week or two ago: 

http://code.databio.org/pypiper/changelog/

and within the next week we will have a new release of looper, peppy, and caravel:

https://github.com/pepkit/looper/pull/152

https://github.com/pepkit/peppy/pull/260

https://github.com/pepkit/caravel/pull/67

So you might want to check those out, early next week

**Comment by rcorces** [comment]
awesome!

**Comment by nsheff** [comment]
did that work for you?

**Comment by rcorces** [comment]
yep
